# Generated by Django 4.2.7 on 2023-11-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translatorApp', '0002_video_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='srt_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
